swagger: "2.0"
info:
  description: FriendsManagement API
  version: 1.0.0
  contact:
    email: leizhe@chinasofti.com
basePath: /v1
paths:
  /Friend/AddFriends:
    post:
      tags:
      - Friend
      description: create a friend connection between two email addresses
      operationId: FriendController.AddFriend
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/dtos.AddFriendInput'
      responses:
        "": {}
  /Friend/GetCommonFriends:
    post:
      tags:
      - Friend
      description: retrieve the common friends list between two email addresses.
      operationId: FriendController.GetCommonFriends
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/dtos.GetCommonFriendsInput'
  /Friend/GetFriends:
    post:
      tags:
      - Friend
      description: retrieve the friends list for an email address
      operationId: FriendController.GetAllFriends
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/dtos.GetAllFriendsInput'
  /Subscribe/AddSubscribe:
    post:
      tags:
      - Subscribe
      description: subscribe to updates from an email address
      operationId: SubscribeController.AddSubscribe
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/dtos.SubscribeInput'
      responses:
        "": {}
  /Subscribe/BlockSubscribe:
    post:
      tags:
      - Subscribe
      description: block updates from an email address.
      operationId: SubscribeController.BlockSubscribe
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/dtos.SubscribeInput'
  /Subscribe/RetrieveSubscribe:
    post:
      tags:
      - Subscribe
      description: retrieve all email addresses that can receive updates from an email
        address.
      operationId: SubscribeController.RetrieveSubscribe
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/dtos.RetrieveSubscribeInput'
definitions:
  dtos.AddFriendInput:
    title: AddFriendInput
    type: object
    properties:
      Friends: {}
  dtos.GetAllFriendsInput:
    title: GetAllFriendsInput
    type: object
    properties:
      Email:
        type: string
  dtos.GetCommonFriendsInput:
    title: GetCommonFriendsInput
    type: object
    properties:
      Friends: {}
  dtos.RetrieveSubscribeInput:
    title: RetrieveSubscribeInput
    type: object
    properties:
      Sender:
        type: string
      Text:
        type: string
  dtos.SubscribeInput:
    title: SubscribeInput
    type: object
    properties:
      Requestor:
        type: string
      Target:
        type: string
tags:
- name: Subscribe
  description: |
    SubscribeController --- Subscribe API
- name: Friend
  description: |
    FriendController --- Friend API
